### ISSUE TITLE
Thanks for your builder, I followed the shell , build successfully but boot failed.

### ISSUE THREAD

**Issue by fun1355** [willzyx-hub/twrp_xiaomi_camellia_builder#1]
I use "camellian-devs/recovery_device_xiaomi_camellia" this "android-12.1" branch as device/xiaomi/camellia. 
And I build as your build.sh does. It builded successfully without errors. but "fastboot boot boot.img" failed. I don't know why.

"fastboot boot ./TWRP-3.7.0_12--20230305-1057.img 
Sending 'boot.img' (65536 KB)                      OKAY [  1.558s]
Booting                                            FAILED (Status read failed (No such device))
fastboot: error: Command failed"

Even I flash boot.img from xiaomi miui ROM, it also failed. WHY????

**Comment by willzyx-hub** [comment]
No such support for flashing I don't own your device so can't tell if you are talking about camellia then `fastboot boot` command is expected doesn't work. Because MediaTek doesn't support these fastboot feature
